package com.jweekend.util;

import org.springframework.jdbc.core.simple.SimpleJdbcDaoSupport;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author Richard Wilkinson - richard.wilkinson@jweekend.com
 * 
 */
public class DatabaseInit extends SimpleJdbcDaoSupport {

	private static final String eventTable = "create table Event (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR, date DATETIME, description VARCHAR, location INTEGER DEFAULT NULL)";
	private static final String locationTable = "create table Location (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR, address VARCHAR)";

	@Transactional
	private void createEventTable() {
		getJdbcTemplate().execute(eventTable);
	}

	@Transactional
	private void createLocationTable() {
		getJdbcTemplate().execute(locationTable);
	}

	public void create() {
		createEventTable();
		createLocationTable();
	}

}
